# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b41524b905f24899b83fe967cae8819399a9b80a3f1a66ed768ab98dc4fbd9d7aaecf8d10a01ab7627c0a9393a5bd1bbd7780585aecfdd4eea654298adec23b

test:
  secret_key_base: 22be524f7a7adc85307e7634f7495544397820df1cb522a23c6755fa9fec72a63a47999df795160a4c18a5a25fb65ad4c85aed62404f48ad06f8e581e8a8352e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
